#!/usr/bin/python

from mutagen.mp3 import MP3
import sys

if(len(sys.argv) != 2):
    print "Usage: audio-length <filename>"
    sys.exit(1)

audio = MP3(sys.argv[1])
len = audio.info.length
print int(round(len))
